using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using GoodCompanyMVC.Auth.Models;
using GoodCompanyMVC.Repositories;
using GoodCompanyMVC.Models;

namespace GoodCompanyMVC.Auth
{
    public class AccountController : Controller
        //FirebaseAuthService is similar to a client manager in web API, dependency injected here
    {
        private readonly IFirebaseAuthService _firebaseAuthService;
        private readonly IUserProfileRepository _userProfileRepository;

        public AccountController(IFirebaseAuthService firebaseAuthService, IUserProfileRepository userProfileRepository)
        {
            _userProfileRepository = userProfileRepository;
            _firebaseAuthService = firebaseAuthService;
        }
//"get" login form
        public IActionResult Login()
        {
            return View();
        }
//FileResult login post: form data
        [HttpPost]
        public async Task<IActionResult> Login(Credentials credentials)
        {
            //server side form validation 
            if (!ModelState.IsValid)
            {

                return View(credentials);
            }
            //userProfile FB auth service to get token
            var fbUser = await _firebaseAuthService.Login(credentials);
            if (fbUser == null)
                //add error message
            {
                ModelState.AddModelError(string.Empty, "Invalid email or password.");
                return View(credentials);
            }

            var userProfile = _userProfileRepository.GetByFirebaseUserId(fbUser.FirebaseUserId);
            if (userProfile == null)
            {
                ModelState.AddModelError(string.Empty, "Unable to Login.");
                return View(credentials);
            }
                //if valid user, log in (private)
            await LoginToApp(userProfile);

            return RedirectToAction("Index", "Home");
        }
        //Form where data model has specific reqs
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(Registration registration)
        {
            //server side form validation - request must conform to model
            if (!ModelState.IsValid)
            {
                return View(registration);
            }
            //send request
            var fbUser = await _firebaseAuthService.Register(registration);
            //catches if not in FB
            if (fbUser == null)
            {
                ModelState.AddModelError(string.Empty, "Unable to register, do you already have an account?");
                return View(registration);
            }
            //Use UserRepo to save new user
            var newUserProfile = new UserProfile
            {
                Email = fbUser.Email,
                FirebaseUserId = fbUser.FirebaseUserId,
                Name = registration.Name
            };

            _userProfileRepository.Add(newUserProfile);

            await LoginToApp(newUserProfile);

            return RedirectToAction("Index", "Homw");
        }

        public async Task<IActionResult> Logout()
        {
            //invalidates MVC cookie
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        private async Task LoginToApp(UserProfile userProfile)
        {
            //cf. logins from earlier projs
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.NameIdentifier, userProfile.Id.ToString()),
                new Claim(ClaimTypes.Email, userProfile.Email),
            };
            //MVC cookie generated by app for auth
            var claimsIdentity = new ClaimsIdentity(
                claims, CookieAuthenticationDefaults.AuthenticationScheme);

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity));
        }
    }
}
